name: utsg
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0-374.1.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  font_awesome_flutter: 10.4.0
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
